apiVersion: v1
kind: Service
metadata:
  name: file-server-persistent-svc
spec:
  type: NodePort
  selector:
    app: file-server-persistent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
