apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-server-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Can be mounted by one pod at a time
  resources:
    requests:
      storage: 5Gi   # Request 5GB of storage
